In [1]:
import numpy as np
import pandas as pd

1. Use numpy to create a one-dimensional vector of length 30 with the numbers 2, 4, and 6 repeating 10 times in a cycle, that is [2 4 6 2 4 6 etc. ].
Do not simply type all 30 numbers in. Rather, use broadcasting.

In [2]:
#create an array with 10 times 2,4,6
a = np.array([2,4,6]*10)
#flatten it and convert to int so there is no .
print(a.flatten().astype(int))

[2 4 6 2 4 6 2 4 6 2 4 6 2 4 6 2 4 6 2 4 6 2 4 6 2 4 6 2 4 6]


2. Create a 5 by 5 array of ones in numpy and then frame it with a border of zeros (so that the first and fifth rows and the first and fifth columns are zero.) The nine interior values remain one.

In [3]:
#initiate the 5*5 array of ones
a = np.ones([5,5])
#convert first and last row to 0
a[0]=a[-1]=0
#convert first and last col to 0
a[:,[0, -1]]=0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

3. Create an 8x8 numpy array such that it resembles the chess board pattern where 1 means white and 2 means black. The lower right "square" should be white (1).

In [4]:
#initialize 8*8 arrays of 1
a = np.ones([8,8])
# convert odd col on even row to 2, then the other way around
a[::2,1::2] =a[1::2,::2] = 2
a

array([[1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [2., 1., 2., 1., 2., 1., 2., 1.]])

In [5]:
#another way: organize 4 1,2 and 2,1, then reshape
a = np.array([[1,2]*4 + [2,1]*4]*4).reshape((8,8))
a

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1, 2, 1]])

4. Create a 13 by 13 array such that the middlemost element is 6. This 6 should be surrounded by all 5's which in turn should be surrounded by 4's, etc. until the edges of the array contain 0's.
Hint: one way to do this is with numpy’s "pad" method.
Also, compute the sum of the numbers in the resulting array.


In [6]:
# start by a 6 in the middle
a = np.ones((1,1))*6
# each time surround the middle with 5 till 0
for i in range(5,-1,-1):
    a = np.pad(a, pad_width=1, constant_values=i)
print(a)
print('sum of the array is: '+str(sum(sum(a))))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 3. 3. 3. 3. 3. 3. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 4. 4. 4. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 5. 5. 5. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 5. 6. 5. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 5. 5. 5. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 4. 4. 4. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 3. 3. 3. 3. 3. 3. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
sum of the array is: 286.0


5. Given the 2D numpy array created with the following list:
[[12, -np.inf, 2, 3], [10, -np.inf, -np.inf, 4], [11, 1, 5, 6]]
Replace the negative infinity values with the average of the positive values in the array.
Thus, the negative infinity values in this case should be replaced by 6 as
(12+2+3+10+4+11+1+5+6)/9 = 6. Calculate this average programmatically (do not just
plug the value 6 in manually).

In [7]:
a = [[12, -np.inf, 2, 3], [10, -np.inf, -np.inf, 4], [11, 1, 5, 6]]
#a function to get mean
def mean(a):
    sum = 0
    len = 0
    for i in a:
        for j in i:
            if(j!= -np.inf):
                sum+=j
                len+=1
    return sum/len
a

[[12, -inf, 2, 3], [10, -inf, -inf, 4], [11, 1, 5, 6]]

In [8]:
# replace -np.inf with mean
df=pd.DataFrame([[12, -np.inf, 2, 3], [10, -np.inf, -np.inf, 4], [11, 1, 5, 6]])
df=df.replace(-np.inf, mean(a))
df

0    1    2  3
0  12  6.0  2.0  3
1  10  6.0  6.0  4
2  11  1.0  5.0  6

6. Our class data folder is here:
https://drive.google.com/drive/folders/1-GKCGczNYt_4hBECuNBytOPX7QXBxBVS?usp=sharing
Using pandas, import the file "numbers.csv" in our class data folder into a dataframe.
Given this dataframe, which has ten columns, num1 to num10, add a new column
named “fourth_smallest” which contains the fourth unique smallest value in each row of
the dataframe.

In [9]:
numbers = pd.read_csv("numbers.csv")
#apply sort and extract the fourth unique smallest value 
numbers["fourth_smallest"] = numbers.apply(lambda n: np.sort(np.unique(n))[3], axis=1)
numbers

num1  num2  num3  num4  num5  num6  num7  num8  num9  num10  \
0     80    99    17    33    49    94    96    70    37     51   
1     54    63    30     8     3    73    52    84     8     42   
2     93    82    22    55    80    49    44    67    63     55   
3     74    31    54    75    11    50    59    85    15     66   
4     75    34     4    32    80     8    28    36    85     27   
5     92    15    30    68    68    91    31    44    21     22   
6     84     5    32    15    50    96    60    23    12     84   
7     35    49    75    77    45    75    30    84    35     10   
8     52    30     4    72    76    26    48    16    24     53   
9     17    75    70    16    23    16    35    65    21     67   
10    86    19    65    55    15    95    30    95    69     81   
11    29    23    97    19    29    36    14    11    62     15   
12    63    49    62    58    46    48    75    97    76     86   
13    64    35     8    45    65    49    44    94    32     12   
14    23    38    53    45    72    52    19    70    56     45   
15    76    53    10    43    67    36    53    41    47     72   
16    16    54     1    42    69    65    97    89    32     43   
17    59    90    65    46    91    73    53    92    63     17   
18    89     1    26    62    16    15    16    28    99     86   
19    55    80    82    67    86    54    10    83    57      9   

    fourth_smallest  
0                49  
1                42  
2                55  
3                50  
4                28  
5                30  
6                23  
7                45  
8                26  
9                23  
10               55  
11               19  
12               58  
13               35  
14               45  
15               43  
16               42  
17               59  
18               26  
19               55

7. Using pandas, import the file "meals.csv" in our class data folder into a dataframe.
Each row represents the cost of a meal of a particular type (cuisine, e.g., Indian, Italian,
Chinese, etc.)
Given the dataframe, find the five cuisines with the lowest minimum meal prices, the
lowest one first.

In [10]:
meals = pd.read_csv("meals.csv")
price = meals['price']
#slice to get rid of $
meals['price2'] = pd.Series(float(i[1:]) for i in price)
#use groupby to sort and get the min
meals.groupby('cuisine')['price2'].min().sort_values()[:5]

cuisine
Korean      5.17
Chinese     5.20
Mexican     5.31
Lebanese    5.45
Italian     5.63
Name: price2, dtype: float64

8. Again using the meals dataframe, find the total number of meals and the average, minimum, and maximum price of a meal for each cuisine, and the standard deviation of the prices of meals in each cuisine, sorted in ascending order by average price.

In [11]:
count = meals.groupby('cuisine').count()['id']
#get all the central tendencies we need
cp=meals.groupby('cuisine')['price2']
mean = cp.mean()
min = cp.min()
max = cp.max()
std = cp.std()
#put them together in a dataframe
m = pd.DataFrame([count, mean, min, max, std], index = ['count','mean','min','max','std']).T
m.sort_values(by = 'mean')

count       mean   min    max        std
cuisine                                           
Italian    89.0  48.759101  5.63  97.62  26.235998
Thai      109.0  50.667156  6.42  98.90  26.984194
Korean    112.0  50.852143  5.17  99.80  29.708550
Mexican   109.0  51.336789  5.31  98.42  26.266314
French     83.0  51.863373  5.93  97.38  25.875529
Spanish    84.0  52.008571  7.01  99.73  28.741630
Greek     105.0  52.282095  6.54  98.37  26.212057
Lebanese  100.0  52.528200  5.45  98.02  25.835318
Chinese   102.0  52.767451  5.20  98.38  27.305883
Indian    107.0  55.743458  6.89  96.59  26.588554

9. Given the following dataframe that gives for each student ID a list of their courses (A through F), create a new dataframe that tells us the number of students enrolled in each particular course (A through F) and sort them in a descending order based on number of students.
students = pd.DataFrame(
 {
 "id": range(101, 113),
 "courses": [
 ["A", "B", "C"],
 ["A", "B", "E"],
 ["B", "D", "E"],
 ["C", "D", "F"],
 ["A", "D", "F"],
 ["B", "C", "E"],
 ["A", "D", "E"],
 ["C", "E", "F"],
 ["D", "E", "F"],
 ["B", "E", "F"],
 ["A", "E", "F"],
 ["C", "D", "F"],
 ],
 }
The pandas “explode” method will help here; see what happens when you use it on the
“courses” column.

In [12]:
students = pd.DataFrame(
{
 "id": range(101, 113),
 "courses": [
 ["A", "B", "C"],
 ["A", "B", "E"],
 ["B", "D", "E"],
 ["C", "D", "F"],
 ["A", "D", "F"],
 ["B", "C", "E"],
 ["A", "D", "E"],
 ["C", "E", "F"],
 ["D", "E", "F"],
 ["B", "E", "F"],
 ["A", "E", "F"],
 ["C", "D", "F"],
 ],
})

#use explode and count to get the number for each course
n=students.explode("courses").groupby("courses").count()
#sort in descending order and rename the column
n=n.sort_values(by="id",ascending=False).rename(columns={"id":"Number of Students enrolled"})
n

Number of Students enrolled
courses                             
E                                  8
F                                  7
D                                  6
A                                  5
B                                  5
C                                  5

10. Using pandas, import the file "stock_prices.csv" in our class data folder into a dataframe.
Given the dataframe, find the difference between the high and low prices (high minus low) and store this in a new column called "spread". Then sort the dataframe in-place by ticker and then spread and display the modified dataframe.

In [13]:
stock = pd.read_csv('stock_prices.csv')
#add a col spread with the difference between high and low
stock['spread'] = stock['high']-stock['low']
#sort the values based on spread and ticker
stock = stock.sort_values(by=['ticker','spread'])
stock

date        open        high         low       close   adj close  \
25  2022-10-04  145.029999  146.220001  144.259995  146.100006  146.100006   
31  2022-10-12  139.130005  140.360001  138.160004  138.339996  138.339996   
27  2022-10-06  145.809998  147.539993  145.220001  145.429993  145.429993   
34  2022-10-17  141.070007  142.899994  140.270004  142.410004  142.410004   
30  2022-10-11  139.899994  141.350006  138.220001  138.979996  138.979996   
..         ...         ...         ...         ...         ...         ...   
61  2022-10-24  205.820007  213.500000  198.589996  211.250000  211.250000   
47  2022-10-04  250.520004  257.500000  242.009995  249.440002  249.440002   
54  2022-10-13  208.300003  222.990005  206.220001  221.720001  221.720001   
44  2022-09-29  282.760010  283.649994  265.779999  268.209991  268.209991   
55  2022-10-14  224.009995  226.259995  204.160004  204.990005  204.990005   

       volume ticker     spread  
25   87830100   AAPL   1.960007  
31   70433700   AAPL   2.199997  
27   68402200   AAPL   2.319992  
34   85250900   AAPL   2.629990  
30   77033700   AAPL   3.130005  
..        ...    ...        ...  
61  100446800   TSLA  14.910004  
47  109578500   TSLA  15.490005  
54   91483000   TSLA  16.770004  
44   77620600   TSLA  17.869995  
55   93898700   TSLA  22.099991  

[132 rows x 9 columns]